version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
    volumes:
      - ./backend:/app/src
    command: CompileDaemon --build="go build -o main ." --command=./main
    networks:
      - backend

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5332:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
